[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
ouro_c_subscriptions = "7c1tGePFVT3ztPEESfzG7gFqYiCJUDjFa7PCeyMSYtub"

[programs.devnet]
ouro_c_subscriptions = "7c1tGePFVT3ztPEESfzG7gFqYiCJUDjFa7PCeyMSYtub"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
